### Broadcasting
- You can add scalar to a vector  and numpy will add it each element in the vector
- Similarly we can add vector to a matrix 

In [4]:
import numpy as np
x = np.array([1,2,3,4])
print(x+4) #broadcasting 

[5 6 7 8]


In [5]:
a = [1,2,3,4]# lsit can't be added like that
print(a+4)

TypeError: can only concatenate list (not "int") to list

In [6]:
matrix = np.array([[10,20,30,40],[60,70,80,90]])
print(matrix)
print(matrix + x)#matrix and vector can be added here .# each row added with the 
#vector 10+ 1, 20+1 ..., 60+1 , 70+1 ..

[[10 20 30 40]
 [60 70 80 90]]
[[11 22 33 44]
 [61 72 83 94]]


### Matrix Multiplication
- also referred as dot product 

### Element - wise Multiplication

In [7]:
A = np.array([[1, 2], [3, 4]])
print(A.shape, A.ndim)

(2, 2) 2


In [8]:
B = np.array([[0,2],[3,2]])

In [9]:
A*B # a11*b11 , a22*b22, a12*b12, a21*b21

array([[0, 4],
       [9, 8]])

In [10]:
np.dot(A,B) # matrix multiplication 

array([[ 6,  6],
       [12, 14]])

### Norms

In [11]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [12]:
np.dot(A, A.T) #l2 norm square, near the origin the derivative is slow for l2 norm

14

### L1 norm = abosolute values of the elements

In [16]:
x = np.array([-6,3,10])
lp2 = np.linalg.norm(x) #by default l2 norm

print(lp2*lp2)
print("%.2f" %lp2)

145.0
12.04


In [56]:
lp1 = np.linalg.norm?

Signature:       np.linalg.norm(x, ord=None, axis=None, keepdims=False)
Call signature:  np.linalg.norm(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function norm at 0x1055360c0>
File:            /opt/anaconda3/lib/python3.11/site-packages/numpy/linalg/linalg.py
Docstring:      
Matrix or vector norm.

This function is able to return one of eight different matrix norms,
or one of an infinite number of vector norms (described below), depending
on the value of the ``ord`` parameter.

Parameters
----------
x : array_like
    Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
    is None. If both `axis` and `ord` are None, the 2-norm of
    ``x.ravel`` will be returned.
ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
    Order of the norm (see table under ``Notes``). inf means numpy's
    `inf` object. The default is None.
axis : {None, int, 2-tuple of ints}, optional.
    If `axis` is an integer, it specifies the axis of `x` along

In [17]:
lp1 = np.linalg.norm(x,ord = 1)
print(int(lp1))

19


In [21]:
lp2 = np.linalg.norm(x, ord = 2)
print("%.2f" % lp2)

12.04


In [22]:
lp_infinty = np.linalg.norm(x, ord = np.inf)

In [23]:
print(lp_infinty) # smallest values

10.0


### Norm of 
- || x + y|| <= ||x|| + ||y||
- ||ax|| = a||x||


### Deteminants
- array atleast be 2 dimensional 

In [26]:
A = np.array([[1, 2], [3, 4]])

In [27]:
int(np.linalg.det(A))

-2

In [28]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
print(np.dot(A, A_inverse)) #AA-1 = Identity matrix

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### Moore Penrose Inverse ( Psuedo Inverse)

In [30]:
pseudo_inverse = np.linalg.pinv(A)
print(pseudo_inverse)
print(np.dot(A,pseudo_inverse))#it will work for both matrix,ie with determinant
# zero also

[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.00000000e+00 -6.66133815e-16]
 [ 8.88178420e-16  1.00000000e+00]]


### Solve A System Of Equations

In [31]:
a = np.array([[2,3], [3,1]])
b = np.array([8,5])

In [32]:
np.linalg.solve(a,b)

array([1., 2.])

In [34]:
a = np.array([[2 , -2, 1],[-1, 2, -1], [2, -4, 1]])

In [35]:
print(a.ndim , a.shape)
print(a)

2 (3, 3)
[[ 2 -2  1]
 [-1  2 -1]
 [ 2 -4  1]]


In [36]:
np.linalg.norm(a, ord = np.inf)

7.0

In [37]:
np.linalg.norm(a) #l2 norm is also called frobenius norm

6.0

In [84]:
A = np.array([[1, -3, 4], [-2, 10, -7], [0, 1, 0], [0, 0, 0]])
B = np.array([[5, 0], [-2, 11], [-3, 12]])

In [85]:
print(A.ndim, B.ndim, A.shape, B.shape)

2 2 (4, 3) (3, 2)


In [86]:
np.dot(A, B)

array([[-1, 15],
       [-9, 26],
       [-2, 11],
       [ 0,  0]])