### Deep_Neural_Network_Implementation
- Two layers 1 hidden + 1 output


In [1]:
# Model Parameters
input_size = 2 # no. of features
layers = [4,3] # no. of neurons in 1st and 2nd layer
output_size = 2

In [12]:
def softmax(a):
    e_power_a = np.exp(a) # Vector
    ans = e_power_a/np.sum(e_power_a, axis = 1, keepdims = True)
    
    return ans

a = np.array([[10,10]])
a_ = softmax(a)
print(a_)


    

[[0.5 0.5]]


In [14]:
b = np.array([[10,10], [20, 20]])
b_ = softmax(b)
print(b_)


[[0.5 0.5]
 [0.5 0.5]]


In [5]:
a = np.array([1,2,3])
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [6]:
a = np.array([[5, 1, 2], [6, 1, 2]])
np.sum(a,axis = 1) # 1 d array

array([8, 9])

In [7]:
a = np.array([[5, 1, 2], [6, 1, 2]])
np.sum(a,axis = 1, keepdims = True) # 2d array

array([[8],
       [9]])

In [3]:
import  numpy as np 

# Neural Network Architecture:

In [13]:
class NeuralNetwork :
    def __init__(self, input_size, layers, output_size):# a constructor
        np.random.seed(0)
#crearting weight matrix for the first hidden layer
        w1 = np.random.randn(input_size, layers[0]) # randn provide normal
        # distribution
        # incantiation of b1
        b1 = np.zeros((1, layers[0]))
        # to access out model later on
        model["w1"] = np.random.randn(input_size, layers[0])
        model['b1'] = np.zeors((1, layers[0]))
# Second Layer
        
        model["w2"] = np.random.randn(layers[0], layers[1])
        model['b2'] = np.zeors((1, layers[1]))
        
# Third Layer/ Output layer
        model["w3"] = np.random.randn(layers[1], output_size)
        model['b3'] = np.zeors((1, output_size))

        self.model = model
    # use for loops for n layered 
        

In [12]:
w1 = np.random.randn(input_size, layers[0])
print(w1, w1.shape)

[[ 0.71659594 -1.69813832 -0.42092309  0.43824262]
 [-1.1863239   2.07209538  0.20123847  0.88258102]] (2, 4)


### Understanding Forward propagation:
- How to pass one example?
- How to pass multiples examples(Vectorization)?
- Writing the code.

In [14]:
import numpy as np

In [ ]:
def forward(self, x):
    w1, w2, w3 = self.model["w1"],self.model["w2"],self.model["w3"],

    b1, b2, b3 = self.model["b1"], self.model["b2"], self.model["b3"]
    
    z1 = np.dot(x, w1) +  b1 # dot product of input layer and the weights
    a1 = np.tanh(z1) # which produces output between -1 and 1 
# tanh is our activation function right here
    z2 = np.tanh(a1, w2) + b2
    a2 = np.tanh(z2)

    z3= np.tanh(a2, w3) + b3
    y_ = softmax(z3)