In [1]:
! pip install nltk

### NLTK
- Corpora -->> It is  collection of texts
- Lexical resources
- It provides you lot of resources and datasets for learning part


In [2]:
import nltk

In [3]:
#nltk.download()
# After executing this , command line pop up

In [4]:
from nltk.corpus import brown

In [5]:
type(brown)

nltk.corpus.util.LazyCorpusLoader

In [6]:
print(brown.categories())
# gives data of different categories

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


In [7]:
# Lets take an example as adventure

In [8]:
print(len(brown.categories()))
# 15 categories in brown method

15


In [9]:
data = brown.sents(categories='adventure')
# get the sentences from the adventure category

In [10]:
data, type(data)

([['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...],
 nltk.corpus.reader.util.ConcatenatedCorpusView)

In [11]:
# list of sentences.

In [12]:
len(data)

4637

In [13]:
data[1]

['He', 'was', 'well', 'rid', 'of', 'her', '.']

In [14]:
' '.join(data[1]) # first sentence in adventure category

'He was well rid of her .'

### Bag of Words Pipeline: Text into numbers and then to classifier


#### Get the data/Corpus

- Real life dataset or nltk.corpus
     
#### Tokenisation, Stopward Removal

- Tokenisation : Process of breaking documents into sentences and then to words.                                                              

- Words are the most minimal token which has meaning.

- Stopward removal : - ex 1)I like movie, 2)I was running, 3) I had a good sleep. All three examples does not contain very meaning full words like - I, was, like, good as these words does not contain much information.

- These words are stop ward words -->> we try to discard these words

#### Stemming/Lemmatization
  
-  To convert different form of words into a base word.
   
-  Ex- Dog is running and dog runs on street.
  
-  stemming convert this in base sentence.
 
  
### Building a Vocab

- List of unique words ; It is a list of after doing stemming , tokenization and stopward removal.
  
- List of this unique word is called vocab.

  
### Vectorization

- We will make a vector of all zeroes with length == len(vocab-ist).
  
- What we will do is : we update our vector's index corresponding to the vocab's index where some random word is avaliable by replacing zero with 1.
  
- Example : - let suppose word "I" is found in vocab list at 50th index ,so we will be updating 50th index of vector to 1.
  
- This is how we convert ourt words into vectors, this process is called vectorization.
  
- Size of vector = size of list vocab  > size of sentence
  
- Order of words doesnot matter
  

  
### Classification
- finally we classify
  

### Tokenisation and stopword Removal
- Doc to Sentences to words.
  

In [15]:
document = """ hey hy how are you , not preety much going on, what about you 
what you did till now"""

example = 'Send all the 50 documents related to chapters 1,2,3 at prateek@cn.com'


In [16]:
from nltk.tokenize import sent_tokenize,word_tokenize
# sent_tokenize-->> breaks doc into sentences.
# and word_tokenize -->> breaks sentences into words.


In [17]:
sentences = sent_tokenize(document)

In [18]:
print(sentences)

[' hey hy how are you , not preety much going on, what about you \nwhat you did till now']


In [19]:
print(type(document), type(sentences))

<class 'str'> <class 'list'>


In [20]:
print(len(sentences)) #oth index contains  three sentences

1


In [21]:
sentences[0]

' hey hy how are you , not preety much going on, what about you \nwhat you did till now'

In [22]:
print(example.split())
#split funtion is unable to seperate numeric value
#'1,2,3' are at 1 single index

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'prateek@cn.com']


In [26]:
print(word_tokenize(example))
# it is able to break "@" seperately
# but still '1,2,3' are at the same index

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'prateek', '@', 'cn.com']


In [40]:
words = word_tokenize(document) 

In [41]:
print(words)

['hey', 'hy', 'how', 'are', 'you', ',', 'not', 'preety', 'much', 'going', 'on', ',', 'what', 'about', 'you', 'what', 'you', 'did', 'till', 'now']


In [44]:
word_tokenize?
# preserve_line= False -->> It is the parameters.
# Returns a tokenized copy of texts -->> means a list of words
# Model works according to the punkt corpus

Signature: word_tokenize(text, language='english', preserve_line=False)
Docstring:
Return a tokenized copy of *text*,
using NLTK's recommended word tokenizer
(currently an improved :class:`.TreebankWordTokenizer`
along with :class:`.PunktSentenceTokenizer`
for the specified language).

:param text: text to split into words
:type text: str
:param language: the model name in the Punkt corpus
:type language: str
:param preserve_line: A flag to decide whether to sentence tokenize the text or not.
:type preserve_line: bool
File:      /opt/anaconda3/lib/python3.11/site-packages/nltk/tokenize/__init__.py
Type:      function

### Stopwords
- Either we can create our own set of words which we want to remove.
- Or we can have it from nltk tool

In [45]:
from nltk.corpus import stopwords
# stopwords works for different language

In [46]:
sw = set(stopwords.words('english'))

In [47]:
print(sw)
#These are the words we need to remove from the sentences 

{'not', 'does', 'above', 'below', 'doesn', 'o', 'she', 'during', 'off', 'over', 'nor', 't', "didn't", 'me', 'to', 'doing', 'whom', 'for', 'most', 'how', 'hasn', 'in', 'himself', 'on', 'out', 'there', 'such', 'this', 'themselves', 'any', "isn't", 'against', 'what', 'are', 'then', 'don', 'mightn', 're', 'again', 'needn', 'be', 'other', "should've", 'you', 'do', 'until', 'before', 'yours', 'of', 'had', 'once', "wouldn't", "shouldn't", 'your', "that'll", 'after', 'and', 'his', 'we', 'their', 'but', 'shan', "don't", "it's", 'he', 'further', 'can', 'into', 'few', 'am', "you're", 'both', 'didn', 'should', 'between', 'our', 'myself', 'him', 'the', 'who', 's', 'couldn', 'hers', 'been', 'same', 'because', 'll', 'won', "couldn't", 'own', 'as', 'wasn', 'while', 'up', 'it', "shan't", "you'll", 'theirs', 'being', 'where', "hasn't", 'd', 'than', 'so', "won't", 'shouldn', 'all', 'having', "aren't", 'when', 'itself', 'or', 'has', "needn't", 'm', 'y', 'ourselves', 'which', "haven't", 'only', 'weren', 'h

In [48]:
len(sw) 

179

In [49]:
def remove_stopwords(text, stopwords):
    useful_text = [ words for words in  text if words not in stopwords]
    return useful_text
    

In [51]:
print(example)

Send all the 50 documents related to chapters 1,2,3 at prateek@cn.com


In [52]:

print(remove_stopwords(example, sw))

['S', 'e', 'n', ' ', 'l', 'l', ' ', 'h', 'e', ' ', '5', '0', ' ', 'c', 'u', 'e', 'n', ' ', 'r', 'e', 'l', 'e', ' ', ' ', 'c', 'h', 'p', 'e', 'r', ' ', '1', ',', '2', ',', '3', ' ', ' ', 'p', 'r', 'e', 'e', 'k', '@', 'c', 'n', '.', 'c']


In [55]:
print(remove_stopwords(example.split(','), sw))

['Send all the 50 documents related to chapters 1', '2', '3 at prateek@cn.com']


In [57]:
text = " i am not worried because I am a very cool guy".split()
# split function converts string into list
print((text))
useful_text = remove_stopwords(text, sw)
print(useful_text)

['i', 'am', 'not', 'worried', 'because', 'I', 'am', 'a', 'very', 'cool', 'guy']
['worried', 'I', 'cool', 'guy']


In [58]:
'not' in sw # not id in stopping word

True

### Tokenization Using Regular Expressions

In [ ]:
#https://www.regexpal.com/ -->. for practice

In [61]:
from nltk.tokenize import RegexpTokenizer

In [63]:
tokenizer = RegexpTokenizer('[a-zA-Z]+') # go to this site for learn more
useful_text = tokenizer.tokenize(example)

In [64]:
print(useful_text)  # 50 is not there

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'prateek', 'cn', 'com']


In [65]:
print(example)

Send all the 50 documents related to chapters 1,2,3 at prateek@cn.com


### Stemming
- Process that transform particular words (verbs, Plurals) into their radical form.
- Preserve the semantics of the sentence without increasing the no. of unique tokens
- Example - Jumps, jumping,jumped, jump ===>>> base word is jump

In [ ]:
text = """ Foxes love to make jumps. the quick brown fox was seen jumping
           over the lovely dog from a 6ft high wall"""

In [67]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [68]:
#create an object of an stemmer 
ps = PorterStemmer()

In [69]:
ps.stem("quickly")

'quickli'

In [70]:
ps.stem("lovely")

'love'

In [71]:
ps.stem("jumps")

'jump'

In [72]:
#SnowballStemmer -->> multilingual
ss = SnowballStemmer('english')

In [73]:
ss.stem('lovely')

'love'

In [74]:
ss.stem('jump-ing')

'jump-'

In [75]:
ss.stem("faithful")

'faith'

### Lemmanization

In [76]:
from nltk.stem import WordNetLemmatizer

In [77]:
wn = WordNetLemmatizer()

In [78]:
wn.lemmatize('jump-ing')

'jump-ing'

In [79]:
wn.lemmatize("jumps")

'jump'

### Vectorization of words 

In [83]:
corpus = [ 
'Indian cricket team will win world cup, says capt. rohit sharma , world cup will be held in barbados'
'I will get good placement in upcoming summer says confident Omkar'
'The nobel laurate won the hearts of the people'
'The movie Raazi is an exciting Indian spy thriller based upon a real story'
]
#we have four documents ,We create 1 feature vector for each document
#vocab = across all the documents we will find the unique words
#word "Indian" appears at 7th index in vocab-list, then at the 7th index
#we will update 1 at the 7th index
#here vocab data is an dictionary
#automate every work using sklearn

In [84]:
from sklearn.feature_extraction.text import CountVectorizer

In [85]:
cv = CountVectorizer()

In [87]:
vectorized_corpus = cv.fit_transform(corpus)
# fit method going to learn the dictionary
# tranform method is going to convert into vectorized form

In [88]:
vectorized_corpus

<1x40 sparse matrix of type '<class 'numpy.int64'>'
	with 40 stored elements in Compressed Sparse Row format>

In [89]:
type(vectorized_corpus)

scipy.sparse._csr.csr_matrix

In [90]:
vectorized_corpus?

Type:        csr_matrix
String form:
(0, 14)	2
           (0, 6)	1
           (0, 31)	1
           (0, 36)	3
           (0, 37)	1
           (0, 39)	2
           (0, 7)	2
           (0, 26)	2
           ( <...> 5)	1
           (0, 0)	1
           (0, 8)	1
           (0, 28)	1
           (0, 33)	1
           (0, 2)	1
           (0, 35)	1
           (0, 24)	1
           (0, 29)	1
File:        /opt/anaconda3/lib/python3.11/site-packages/scipy/sparse/_csr.py
Docstring:  
Compressed Sparse Row matrix

This can be instantiated in several ways:
    csr_array(D)
        with a dense matrix or rank-2 ndarray D

    csr_array(S)
        with another sparse matrix S (equivalent to S.tocsr())

    csr_array((M, N), [dtype])
        to construct an empty matrix with shape (M, N)
        dtype is optional, defaulting to dtype='d'.

    csr_array((data, (row_ind, col_ind)), [shape=(M, N)])
        where ``data``, ``row_ind`` and ``col_ind`` satisfy the
        relationship ``a[row_ind[k], col_ind[k]]

In [ ]:
#In the zeroth sentence the first word is found at 6th index in the vocab

In [91]:
vectorized_corpus_array = vectorized_corpus.toarray()

In [92]:
vectorized_corpus_array.shape

(1, 40)

In [93]:
vectorized_corpus_array[0] # first sentence

array([1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 2])

In [95]:
vectorized_corpus_array[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [94]:
len(vectorized_corpus_array[0])


40

In [96]:
cv.vocabulary_


{'indian': 14,
 'cricket': 6,
 'team': 31,
 'will': 36,
 'win': 37,
 'world': 39,
 'cup': 7,
 'says': 26,
 'capt': 4,
 'rohit': 25,
 'sharma': 27,
 'be': 3,
 'held': 12,
 'in': 13,
 'barbadosi': 1,
 'get': 9,
 'good': 10,
 'placement': 22,
 'upcoming': 34,
 'summer': 30,
 'confident': 5,
 'omkarthe': 20,
 'nobel': 18,
 'laurate': 16,
 'won': 38,
 'the': 32,
 'hearts': 11,
 'of': 19,
 'peoplethe': 21,
 'movie': 17,
 'raazi': 23,
 'is': 15,
 'an': 0,
 'exciting': 8,
 'spy': 28,
 'thriller': 33,
 'based': 2,
 'upon': 35,
 'real': 24,
 'story': 29}

In [97]:
len(cv.vocabulary_)

40

In [98]:
(cv.vocabulary_.keys())

dict_keys(['indian', 'cricket', 'team', 'will', 'win', 'world', 'cup', 'says', 'capt', 'rohit', 'sharma', 'be', 'held', 'in', 'barbadosi', 'get', 'good', 'placement', 'upcoming', 'summer', 'confident', 'omkarthe', 'nobel', 'laurate', 'won', 'the', 'hearts', 'of', 'peoplethe', 'movie', 'raazi', 'is', 'an', 'exciting', 'spy', 'thriller', 'based', 'upon', 'real', 'story'])

In [99]:
len(cv.vocabulary_.keys())

40

### Reverse Mapping

In [100]:
numbers = vectorized_corpus_array[0]
numbers

array([1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 2])

In [102]:
cv.inverse_transform(numbers)

ValueError: Expected 2D array, got 1D array instead:
array=[1 1 1 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 3
 1 1 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

### More ways to create features
- Unigram - every word as a feature
- Bigram - 2 words combined as a feature
- Trigram
- n-gram
- TF-IDF Normalization

In [103]:
sent1 = ["this is good movie"]
sent2 = ["this is not a good movie"]
#both have good movie 
# this confuses our classififer 
# it can predict both movie as good

In [104]:
cv = CountVectorizer()

In [110]:
doc = [sent1[0],sent2[0]]

In [111]:
doc

['this is good movie', 'this is not a good movie']

In [112]:
doc = cv.fit_transform(doc)

In [113]:
doc?

Type:        csr_matrix
String form:
  (0, 4)	1
  (0, 1)	1
  (0, 0)	1
  (0, 2)	1
  (1, 4)	1
  (1, 1)	1
  (1, 0)	1
  (1, 2)	1
  (1, 3)	1
File:        /opt/anaconda3/lib/python3.11/site-packages/scipy/sparse/_csr.py
Docstring:  
Compressed Sparse Row matrix

This can be instantiated in several ways:
    csr_array(D)
        with a dense matrix or rank-2 ndarray D

    csr_array(S)
        with another sparse matrix S (equivalent to S.tocsr())

    csr_array((M, N), [dtype])
        to construct an empty matrix with shape (M, N)
        dtype is optional, defaulting to dtype='d'.

    csr_array((data, (row_ind, col_ind)), [shape=(M, N)])
        where ``data``, ``row_ind`` and ``col_ind`` satisfy the
        relationship ``a[row_ind[k], col_ind[k]] = data[k]``.

    csr_array((data, indices, indptr), [shape=(M, N)])
        is the standard CSR representation where the column indices for
        row i are stored in ``indices[indptr[i]:indptr[i+1]]`` and their
        corresponding values a

In [114]:
doc_array = doc.toarray()

In [115]:
doc_array

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [116]:
sent3 = ["this is a good movie but actor is not present"]
sent1 = ["this is good movie"]
sent2 = ["this is not a good movie"]
# again It can confuse our classifier 
# as sentence 3 causing for sentence 2 also, as it can predict the movie as 
# a good one
# for this we need bi grams

In [117]:
cv = CountVectorizer(ngram_range=(2,2))# here it is bigram,
#by default CountVectorizer is unigram feature

In [118]:
docs = [sent1[0],sent2[0]]
docs

['this is good movie', 'this is not a good movie']

In [119]:
docs = cv.fit_transform(docs)
# now our output is chaged

In [120]:
doc_array

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [122]:
docs_array = docs.toarray()
doc_array
# both are different answers

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [123]:
cv.vocabulary_
# here this is , is good are as a single feature

{'this is': 4, 'is good': 1, 'good movie': 0, 'is not': 2, 'not good': 3}

In [124]:
cv = CountVectorizer(ngram_range=(3,3))

In [125]:
doc3 = [sent1[0],sent2[0]]

In [126]:
doc3

['this is good movie', 'this is not a good movie']

In [127]:
doc3 = cv.fit_transform(doc3).toarray()

In [128]:
doc3

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]])

In [129]:
cv.vocabulary_
# now 3 words as a feature

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

### Tf - idf Normalisation
- Avoid features that occur very often , because they contain less information

  
- Information decreases as the number of occurence increases acorss  different type of documents

  
- So we define another term-term-document-frequency which associates a weight with every

  
-  for example sports occur several times in sport document , as the frequency of these words is more , less it is important

  
-  More frequent words contains less info more likely.

  
-  Example leader occurs very less time in politics but whenever it comes we know it is related to politics

  
-  TF-IDF is made up of two terms Term frequency and Inverse Document Frequency.

  
-  term frequency - tf(t,d) where t is term-frqency and d is document

  
-  idf - inverse document function(t,d) = log(N/(1+ count(t,D)),where  coutn(t,D) means how many time this term t occured across the entire document D, N is the total no of document.

  
-  for example "good" word appear thrice in the corpus which has 3 documents ie N =3 , count(t,D) =3{for a given document the term frequency is 1.
-  hence log(1) = 0, which implies good word has very less contribution.
   
-  This implies , word significnce increases as the number start approaching towards the 1, ie word will have a higher weight
-  weight will between 0 and 1.


  

In [134]:
sent1 = "this is good movie"
sent2 = 'this is not a good movie'
sent3 = 'this is a good movie but actor was not present'

In [135]:

corpus = [sent1,sent2,sent3]


In [136]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [137]:
tfidf = TfidfVectorizer()

In [138]:
vectorised_corpus = tfidf.fit_transform(corpus)

In [139]:
vectorised_corpus_array = vectorised_corpus.toarray()

In [140]:
print(vectorised_corpus_array)

[[0.         0.         0.5        0.5        0.5        0.
  0.         0.5        0.        ]
 [0.         0.         0.42040099 0.42040099 0.42040099 0.54134281
  0.         0.42040099 0.        ]
 [0.40914568 0.40914568 0.24164803 0.24164803 0.24164803 0.31116583
  0.40914568 0.24164803 0.40914568]]


In [141]:
print(tfidf.vocabulary_)

{'this': 7, 'is': 3, 'good': 2, 'movie': 4, 'not': 5, 'but': 1, 'actor': 0, 'was': 8, 'present': 6}
