### Working with Numpy- for mathematical operations

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,2,344,5])
a

array([  1,   2,   2, 344,   5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape #return a tuple

(5,)

In [6]:
b = np.array([[1],[2],[3],[4],[5]])

In [7]:
x = b.shape
print(x,x[1])

(5, 1) 1


In [8]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
b[0][0]

1

In [10]:
c = np.array([[1,2,3],[4,5,6]])

In [11]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
c.shape

(2, 3)

In [13]:
c[1][1]

5

In [14]:
a = np.zeros((3,3))

In [15]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
b = np.zeros((2,3))

In [17]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
c = np.full((3,2),5) # array with all same elements

In [19]:
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [20]:
c.T

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
d = np.eye(4) # identity matrix of 4,4

In [22]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
d = np.eye(4,4)

In [24]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
Matrix = np.random.random((2,3))

In [26]:
Matrix

array([[0.14695449, 0.19396625, 0.05041126],
       [0.89409189, 0.46128679, 0.96485431]])

In [27]:
print(Matrix[:, 2])

[0.05041126 0.96485431]


In [28]:
Matrix2 = np.random.randint(1, 20, (5,4))
Matrix2

array([[12, 15,  6,  5],
       [16, 16, 12,  1],
       [ 7,  9, 15,  8],
       [ 6, 16, 14, 15],
       [ 8,  5,  6, 18]])

In [29]:
#setting rows and columns in matrix

In [30]:
z = np.zeros((3,3))
print(z)
z[0,:] = 5
print(z)
z[1:3,0:3] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 5. 5.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 5. 5.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [31]:
#Data types
print(z.dtype, type(z))

float64 <class 'numpy.ndarray'>


In [32]:
z = np.zeros((3,3),dtype = int)
print(z)
z[0,:] = 5
print(z)
z[1:3,0:3] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[5 5 5]
 [0 0 0]
 [0 0 0]]
[[5 5 5]
 [7 7 7]
 [7 7 7]]


In [33]:
print(z.dtype, type(z))

int64 <class 'numpy.ndarray'>


In [34]:
#mathematical Operations 

In [35]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x + y, x- y , np.subtract(x,y), x*y, np.multiply(x,y), x/y)

[[ 6  8]
 [10 12]] [[-4 -4]
 [-4 -4]] [[-4 -4]
 [-4 -4]] [[ 5 12]
 [21 32]] [[ 5 12]
 [21 32]] [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [37]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
print(a.dot(b))

80


In [38]:
print(np.cross(a,b))

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
np.sum(a)

In [39]:
sum(a)

10

In [40]:
np.sum(a, axis = 0)

10

In [41]:
x

array([[1, 2],
       [3, 4]])

In [42]:
np.sum(x, axis = 0) # row wise sum

array([4, 6])

In [43]:
np.sum(x, axis = 1 ) # column wise

array([3, 7])

In [46]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[1296 2401 4096 6561]


In [47]:
c =np.stack((a,b), axis = 0)

In [48]:
c

array([[   1,    2,    3,    4],
       [1296, 2401, 4096, 6561]])

In [50]:
d = np.stack((a,b), axis = 1)
d

array([[   1, 1296],
       [   2, 2401],
       [   3, 4096],
       [   4, 6561]])

In [51]:
#reshape a numpy array 

In [56]:
print(d)

[[   1 1296    2 2401]
 [   3 4096    4 6561]]


In [60]:
d = d.reshape((4,2))
d

array([[   1, 1296],
       [   2, 2401],
       [   3, 4096],
       [   4, 6561]])

In [61]:
d = d.reshape((8,1))

In [62]:
d

array([[   1],
       [1296],
       [   2],
       [2401],
       [   3],
       [4096],
       [   4],
       [6561]])

In [63]:
d =d.reshape((4,-1))

In [64]:
d

array([[   1, 1296],
       [   2, 2401],
       [   3, 4096],
       [   4, 6561]])

### Numpy Random Module 

In [71]:
a = np.arange(10)
print(a, a+5)

[0 1 2 3 4 5 6 7 8 9] [ 5  6  7  8  9 10 11 12 13 14]


In [75]:
np.random.shuffle(a)
print(a)

[7 6 0 9 3 1 5 4 8 2]


In [76]:
#returns values from a standard Noraml distribution
a = np.random.rand(2,3)
print(a)

[[0.94050311 0.24900189 0.18827249]
 [0.36751708 0.24243777 0.39313827]]


In [77]:
a = np.random.randint(1,20,(3,4))
a

array([[18,  2, 13, 16],
       [14, 13, 18, 13],
       [12,  8,  4,  8]])

In [81]:
#randomly pick one element from array
element = np.random.choice(a)
element

ValueError: a must be 1-dimensional

In [95]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
element = np.random.choice(a)
element

9

In [97]:
element = np.random.choice(a)
element

6

In [102]:
np.random.seed(1) #random seeding
np.random.shuffle(a)
print(a)


[6 3 7 8 2 9 5 4 1]


In [99]:
np.random.seed(1)
np.random.shuffle(a)
print(a)


[6 7 5 4 3 9 2 8 1]


In [100]:
np.random.seed(1)
np.random.shuffle(a)
print(a)


[1 5 2 8 7 6 3 4 9]


### Statistical Computation Using Numpy

In [121]:
a = np.array([[1,2,3,34,44],[54,67,-3,99,108]])
print(a)
print(np.min(a))
print(np.min(a, axis = 0),np.min(a, axis = 1))
print(np.size(a))

[[  1   2   3  34  44]
 [ 54  67  -3  99 108]]
-3
[ 1  2 -3 34 44] [ 1 -3]
10


In [111]:
b = np.array([1,2,3,4,5])
mean = sum(b)/5
print(mean, np.mean(b, axis = 0))

3.0 3.0


In [112]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [115]:
print(np.mean(c), np.average(c))

2.4 2.4


In [114]:
w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

2.066666666666667


### Std Deviation

In [116]:
u = np.mean(c)
std_deviation = np.sqrt(np.mean(abs(c-u)**2))
std_deviation

1.854723699099141

In [118]:
std_deviation = np.std(c)
std_deviation

1.854723699099141

In [119]:
print(np.var(c))

3.4400000000000004


In [120]:
print(np.size(c))

5


In [123]:
print(list(a))
print(a.tolist())

[array([ 1,  2,  3, 34, 44]), array([ 54,  67,  -3,  99, 108])]
[[1, 2, 3, 34, 44], [54, 67, -3, 99, 108]]


In [131]:
print(a.view())

[[  1   2   3  34  44]
 [ 54  67  -3  99 108]]


In [132]:
print(a.copy)

<built-in method copy of numpy.ndarray object at 0x117c9c390>


In [129]:
print(a.copyto())

AttributeError: 'numpy.ndarray' object has no attribute 'copyto'

In [134]:
print(a[np.where((a >= 5) & (a <= 60))])

[34 44 54]


In [137]:
a[np.all((a >= 5) & (a <= 90))]

array([], shape=(0, 2, 5), dtype=int64)

In [139]:
print(a[(a >= 5) & (a <= 60)])

[34 44 54]


In [142]:
print(a.resize(5,2))

None


In [143]:
print(a.size)

10


In [148]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [149]:
print(np.hstack((a,b)))

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [150]:
print(np.concatenate((a,b), axis = 0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [151]:
print(np.concatenate((a,b), axis = 1))

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [152]:
img = np.arange(3*3*3).reshape(3,3,3)
img

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [153]:
print(img[::-1])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [155]:
print(img[2,1,0],img[[2,1,0], :,:])

21 [[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [156]:
print(img[:, ::-1])

[[[ 6  7  8]
  [ 3  4  5]
  [ 0  1  2]]

 [[15 16 17]
  [12 13 14]
  [ 9 10 11]]

 [[24 25 26]
  [21 22 23]
  [18 19 20]]]
